### ISSUE TITLE
[Bug] Error on Manjaro KDE (Anki 2.1.55)

### ISSUE THREAD

**Issue by Exponent4806** [abdnh/create-subs2srs-cards-with-mpv-video-player#2]
Bug Message after installing the add-on.
OS: Manjaro KDE Stable
Anki Version ⁨2.1.55 (01caec2a)⁩
Python 3.10.8 Qt 6.4.1 PyQt 6.4.0

Fehler
Eine der installierten Erweiterungen konnte nicht geladen werden. Wenn das Problem weiter besteht, bitte über den Menüpunkt Extras → Erweiterungen die Erweiterungen deaktivieren oder deinstallieren

Beim Laden von '**⁨Create subs2srs cards with mpv  interactive subs⁩'**:
⁨Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/aqt/addons.py", line 247, in loadAddons
    __import__(addon.dir_name)
  File "/home/m/.local/share/Anki2/addons21/832294226/__init__.py", line 1, in <module>
    from . import mpv2anki
  File "/home/m/.local/share/Anki2/addons21/832294226/mpv2anki.py", line 75, in <module>
    import pysubs2
  File "/home/m/.local/share/Anki2/addons21/832294226/vendor/pysubs2/__init__.py", line 1, in <module>
    from .ssafile import SSAFile
  File "/home/m/.local/share/Anki2/addons21/832294226/vendor/pysubs2/ssafile.py", line 1, in <module>
    from collections import MutableSequence
ImportError: cannot import name 'MutableSequence' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
⁩

**Comment by abdnh** [comment]
Hi, can you try this and let me know if it fixes the issue?
[create_sub2srs_cards_with_mpv.zip](https://github.com/abdnh/create-subs2srs-cards-with-mpv-video-player/files/10323004/create_sub2srs_cards_with_mpv.zip)

You'll probably run into another issues like https://github.com/abdnh/intersubs/issues/3 on Linux at the moment.

**Comment by Exponent4806** [comment]
It does work ! Thanks
