### ISSUE TITLE
Windows 10

### ISSUE THREAD

**Issue by adriannedbailo** [abdnh/create-subs2srs-cards-with-mpv-video-player#3]
There is the problem with the add-on. How does it fix?

Anki 2.1.49 (dc80804a) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2023-02-05 18:20:12

Caught exception:
Traceback (most recent call last):
  File "C:\Users\Artur\AppData\Roaming\Anki2\addons21\832294226\mpv2anki.py", line 1543, in start
    "popup_options", self.configManager.popupDict.collect_widget_settings()
  File "C:\Users\Artur\AppData\Roaming\Anki2\addons21\832294226\popup\zim_reader.py", line 73, in collect_widget_settings
    "file": self.file.name,
AttributeError: 'NoneType' object has no attribute 'name'

**Comment by abdnh** [comment]
Please try the new update.
